/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbc.karate.club;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Abhirham
 */
public class studhome extends javax.swing.JFrame {
Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form studhome
     */
    public studhome() {
        initComponents();
        try {
            conn = sqlcon.connecrDB();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "JDBC connction failed");
        }
        filltable("all");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studtable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        sid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT");

        studtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(studtable);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("View Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Add/Update student");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Student id:");

        jButton4.setText("View Parent");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("View Payment History");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jButton4)
                        .addGap(39, 39, 39)
                        .addComponent(jButton5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(sid.getText().equals(""))
            filltable("all");
        else{
            filltable(sid.getText());
            if(studtable.getModel().getRowCount()==0)
                JOptionPane.showMessageDialog(null, "Invalid student ID!");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      if(sid.getText().equals(""))
          JOptionPane.showMessageDialog(null, "Please enter a student number.");
      else{
        String sql="Select s.STU_NUM,CONCAT(STU_FNAME,' ',STU_LNAME) as 'Student Name', CONCAT(F_FNAME,' ',F_LNAME) as 'Father Name',CONCAT(M_FNAME,' ',M_LNAME) as 'Mother Name',PAR_MOB,PAR_EMAIL from STUDENT s, PARENT p where s.STU_NUM=p.STU_NUM and s.STU_NUM='"+sid.getText()+"'";
        try {
            pst = conn.prepareStatement(sql);
//          pst.setString(1, sid.getText());
            rs = pst.executeQuery();
            studtable.setModel(DbUtils.resultSetToTableModel(rs));
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);}
        if(studtable.getModel().getRowCount()==0)
            JOptionPane.showMessageDialog(null, "Student is an adult. Parent details unavailable.");

      }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         if(sid.getText().equals(""))
          JOptionPane.showMessageDialog(null, "Please enter a student number.");
      else{
        String sql="select FEE_RECEIPT_ID,FEE_DATE,FEE_AMOUNT,FEE_DESC from fee where  stu_num ="+sid.getText()+" order by FEE_DATE desc";
        try {
            pst = conn.prepareStatement(sql);
//          pst.setString(1, sid.getText());
            rs = pst.executeQuery();
            studtable.setModel(DbUtils.resultSetToTableModel(rs));
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);}
        if(studtable.getModel().getRowCount()==0)
            JOptionPane.showMessageDialog(null, "Student has not made any payment"); 
         }// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
               conn.close();
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "jdbc closing failed");
           }
        addstud a = new addstud();
       a.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
               conn.close();
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "jdbc closing failed");
           }

        home a=new home();
      a.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studhome().setVisible(true);
            }
        });
    }
    
    public void filltable(String a){
        String sql;
        if(a.equals("all")){
            sql="select T.STU_NUM,T.Name AS 'STU_NAME',T.STU_MOB,T.STU_EMAIL,T.STU_DOB,T.STU_JOIN_DATE,T.Address as 'STU_ADDR', T.RANK_COLOR from \n" +
"(\n" +
"Select s.STU_NUM, CONCAT(STU_FNAME,' ',STU_LNAME) as 'Name',\n" +
" STU_MOB, STU_EMAIL, STU_DOB, STU_JOIN_DATE, \n" +
" CONCAT(STU_APPARTMENT,', ',STU_CITY,', ',STU_STATE,', ',STU_COUNTRY,', ',STU_ZIP) as 'Address',\n" +
" RANK_COLOR, rank() over (partition by s.STU_NUM\n" +
"             order by r.RANK_NUM desc) rnk from STUDENT s\n" +
" left join ACHIEVEMENT a on s.STU_NUM=a.STU_NUM\n" +
" left join RANK_TABLE r on a.RANK_NUM=r.RANK_NUM ) T\n" +
" where T.rnk=1";
//            sql="Select s.STU_NUM, CONCAT(STU_FNAME,' ',STU_LNAME) as 'Name', STU_MOB, STU_EMAIL, STU_DOB, STU_JOIN_DATE, CONCAT(STU_APPARTMENT,', ',STU_CITY,', ',STU_STATE,', ',STU_COUNTRY,', ',STU_ZIP) as 'Address',RANK_COLOR from STUDENT s, ACHIEVEMENT a,RANK_TABLE r where s.STU_NUM=a.STU_NUM and a.RANK_NUM=r.RANK_NUM";
        }else
            sql="Select s.STU_NUM, CONCAT(STU_FNAME,' ',STU_LNAME) as 'Name', STU_MOB, STU_EMAIL, STU_DOB, STU_JOIN_DATE, CONCAT(STU_APPARTMENT,', ',STU_CITY,', ',STU_STATE,', ',STU_COUNTRY,', ',STU_ZIP) as 'Address',RANK_COLOR from STUDENT s, ACHIEVEMENT a,RANK_TABLE r where s.STU_NUM=a.STU_NUM and a.RANK_NUM=r.RANK_NUM and s.STU_NUM='"+a+"' ORDER BY r.RANK_NUM desc";
        
        try {
            pst = conn.prepareStatement(sql);
//          pst.setString(1, sid.getText());
            rs = pst.executeQuery();
            studtable.setModel(DbUtils.resultSetToTableModel(rs));
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sid;
    private javax.swing.JTable studtable;
    // End of variables declaration//GEN-END:variables
}
